using System.Collections.Generic;

namespace HelloApp
{
    public class CountryModel
    {
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public string Iso { get; set; }


        public static List<CountryModel> Countries = new()
        {
            new CountryModel { Name = "Afghanistan", ShortName = "AF", Code = "+93", Iso = "AF" },
            new CountryModel { Name = "Aland Islands", ShortName = "AX", Code = "+358", Iso = "AX" },
            new CountryModel { Name = "Albania", ShortName = "AL", Code = "+355", Iso = "AL" },
            new CountryModel { Name = "Algeria", ShortName = "DZ", Code = "+213", Iso = "DZ" },
            new CountryModel { Name = "AmericanSamoa", ShortName = "AS", Code = "+1684", Iso = "AS" },
            new CountryModel { Name = "Andorra", ShortName = "AD", Code = "+376", Iso = "AD" },
            new CountryModel { Name = "Angola", ShortName = "AO", Code = "+244", Iso = "AO" },
            new CountryModel { Name = "Anguilla", ShortName = "AI", Code = "+1264", Iso = "AI" },
            new CountryModel { Name = "Antarctica", ShortName = "AQ", Code = "+672", Iso = "AQ" },
            new CountryModel { Name = "Antigua and Barbuda", ShortName = "AG", Code = "+1268", Iso = "AG" },
            new CountryModel { Name = "Argentina", ShortName = "AR", Code = "+54", Iso = "AR" },
            new CountryModel { Name = "Armenia", ShortName = "AM", Code = "+374", Iso = "AM" },
            new CountryModel { Name = "Aruba", ShortName = "AW", Code = "+297", Iso = "AW" },
            new CountryModel { Name = "Australia", ShortName = "AU", Code = "+61", Iso = "AU" },
            new CountryModel { Name = "Austria", ShortName = "AT", Code = "+43", Iso = "AT" },
            new CountryModel { Name = "Azerbaijan", ShortName = "AZ", Code = "+994", Iso = "AZ" },
            new CountryModel { Name = "Bahamas", ShortName = "BS", Code = "+1242", Iso = "BS" },
            new CountryModel { Name = "Bahrain", ShortName = "BH", Code = "+973", Iso = "BH" },
            new CountryModel { Name = "Bangladesh", ShortName = "BD", Code = "+880", Iso = "BD" },
            new CountryModel { Name = "Barbados", ShortName = "BB", Code = "+1246", Iso = "BB" },
            new CountryModel { Name = "Belarus", ShortName = "BY", Code = "+375", Iso = "BY" },
            new CountryModel { Name = "Belgium", ShortName = "BE", Code = "+32", Iso = "BE" },
            new CountryModel { Name = "Belize", ShortName = "BZ", Code = "+501", Iso = "BZ" },
            new CountryModel { Name = "Benin", ShortName = "BJ", Code = "+229", Iso = "BJ" },
            new CountryModel { Name = "Bermuda", ShortName = "BM", Code = "+1441", Iso = "BM" },
            new CountryModel { Name = "Bhutan", ShortName = "BT", Code = "+975", Iso = "BT" },
            new CountryModel { Name = "Bolivia, Plurinational State of", ShortName = "BO", Code = "+591", Iso = "BO" },
            new CountryModel { Name = "Bosnia and Herzegovina", ShortName = "BA", Code = "+387", Iso = "BA" },
            new CountryModel { Name = "Botswana", ShortName = "BW", Code = "+267", Iso = "BW" },
            new CountryModel { Name = "Brazil", ShortName = "BR", Code = "+55", Iso = "BR" },
            new CountryModel { Name = "British Indian Ocean Territory", ShortName = "IO", Code = "+246", Iso = "IO" },
            new CountryModel { Name = "Brunei Darussalam", ShortName = "BN", Code = "+673", Iso = "BN" },
            new CountryModel { Name = "Bulgaria", ShortName = "BG", Code = "+359", Iso = "BG" },
            new CountryModel { Name = "Burkina Faso", ShortName = "BF", Code = "+226", Iso = "BF" },
            new CountryModel { Name = "Burundi", ShortName = "BI", Code = "+257", Iso = "BI" },
            new CountryModel { Name = "Cambodia", ShortName = "KH", Code = "+855", Iso = "KH" },
            new CountryModel { Name = "Cameroon", ShortName = "CM", Code = "+237", Iso = "CM" },
            new CountryModel { Name = "Canada", ShortName = "CA", Code = "+1", Iso = "CA" },
            new CountryModel { Name = "Cape Verde", ShortName = "CV", Code = "+238", Iso = "CV" },
            new CountryModel { Name = "Cayman Islands", ShortName = "KY", Code = "+345", Iso = "KY" },
            new CountryModel { Name = "Central African Republic", ShortName = "CF", Code = "+236", Iso = "CF" },
            new CountryModel { Name = "Chad", ShortName = "TD", Code = "+235", Iso = "TD" },
            new CountryModel { Name = "Chile", ShortName = "CL", Code = "+56", Iso = "CL" },
            new CountryModel { Name = "China", ShortName = "CN", Code = "+86", Iso = "CN" },
            new CountryModel { Name = "Christmas Island", ShortName = "CX", Code = "+61", Iso = "CX" },
            new CountryModel { Name = "Cocos (Keeling) Islands", ShortName = "CC", Code = "+61", Iso = "CC" },
            new CountryModel { Name = "Colombia", ShortName = "CO", Code = "+57", Iso = "CO" },
            new CountryModel { Name = "Comoros", ShortName = "KM", Code = "+269", Iso = "KM" },
            new CountryModel { Name = "Congo", ShortName = "CG", Code = "+242", Iso = "CG" },
            new CountryModel
                { Name = "Congo, The Democratic Republic of the Congo", ShortName = "CD", Code = "+243", Iso = "CD" },
            new CountryModel { Name = "Cook Islands", ShortName = "CK", Code = "+682", Iso = "CK" },
            new CountryModel { Name = "Costa Rica", ShortName = "CR", Code = "+506", Iso = "CR" },
            new CountryModel { Name = "Cote d'Ivoire", ShortName = "CI", Code = "+225", Iso = "CI" },
            new CountryModel { Name = "Croatia", ShortName = "HR", Code = "+385", Iso = "HR" },
            new CountryModel { Name = "Cuba", ShortName = "CU", Code = "+53", Iso = "CU" },
            new CountryModel { Name = "Cyprus", ShortName = "CY", Code = "+357", Iso = "CY" },
            new CountryModel { Name = "Czech Republic", ShortName = "CZ", Code = "+420", Iso = "CZ" },
            new CountryModel { Name = "Denmark", ShortName = "DK", Code = "+45", Iso = "DK" },
            new CountryModel { Name = "Djibouti", ShortName = "DJ", Code = "+253", Iso = "DJ" },
            new CountryModel { Name = "Dominica", ShortName = "DM", Code = "+1767", Iso = "DM" },
            new CountryModel { Name = "Dominican Republic", ShortName = "DO", Code = "+1849", Iso = "DO" },
            new CountryModel { Name = "Ecuador", ShortName = "EC", Code = "+593", Iso = "EC" },
            new CountryModel { Name = "Egypt", ShortName = "EG", Code = "+20", Iso = "EG" },
            new CountryModel { Name = "El Salvador", ShortName = "SV", Code = "+503", Iso = "SV" },
            new CountryModel { Name = "Equatorial Guinea", ShortName = "GQ", Code = "+240", Iso = "GQ" },
            new CountryModel { Name = "Eritrea", ShortName = "ER", Code = "+291", Iso = "ER" },
            new CountryModel { Name = "Estonia", ShortName = "EE", Code = "+372", Iso = "EE" },
            new CountryModel { Name = "Ethiopia", ShortName = "ET", Code = "+251", Iso = "ET" },
            new CountryModel { Name = "Falkland Islands (Malvinas)", ShortName = "FK", Code = "+500", Iso = "FK" },
            new CountryModel { Name = "Faroe Islands", ShortName = "FO", Code = "+298", Iso = "FO" },
            new CountryModel { Name = "Fiji", ShortName = "FJ", Code = "+679", Iso = "FJ" },
            new CountryModel { Name = "Finland", ShortName = "FI", Code = "+358", Iso = "FI" },
            new CountryModel { Name = "France", ShortName = "FR", Code = "+33", Iso = "FR" },
            new CountryModel { Name = "French Guiana", ShortName = "GF", Code = "+594", Iso = "GF" },
            new CountryModel { Name = "French Polynesia", ShortName = "PF", Code = "+689", Iso = "PF" },
            new CountryModel { Name = "Gabon", ShortName = "GA", Code = "+241", Iso = "GA" },
            new CountryModel { Name = "Gambia", ShortName = "GM", Code = "+220", Iso = "GM" },
            new CountryModel { Name = "Georgia", ShortName = "GE", Code = "+995", Iso = "GE" },
            new CountryModel { Name = "Germany", ShortName = "DE", Code = "+49", Iso = "DE" },
            new CountryModel { Name = "Ghana", ShortName = "GH", Code = "+233", Iso = "GH" },
            new CountryModel { Name = "Gibraltar", ShortName = "GI", Code = "+350", Iso = "GI" },
            new CountryModel { Name = "Greece", ShortName = "GR", Code = "+30", Iso = "GR" },
            new CountryModel { Name = "Greenland", ShortName = "GL", Code = "+299", Iso = "GL" },
            new CountryModel { Name = "Grenada", ShortName = "GD", Code = "+1473", Iso = "GD" },
            new CountryModel { Name = "Guadeloupe", ShortName = "GP", Code = "+590", Iso = "GP" },
            new CountryModel { Name = "Guam", ShortName = "GU", Code = "+1671", Iso = "GU" },
            new CountryModel { Name = "Guatemala", ShortName = "GT", Code = "+502", Iso = "GT" },
            new CountryModel { Name = "Guinea", ShortName = "GN", Code = "+224", Iso = "GN" },
            new CountryModel { Name = "Guinea-Bissau", ShortName = "GW", Code = "+245", Iso = "GW" },
            new CountryModel { Name = "Guyana", ShortName = "GY", Code = "+595", Iso = "GY" },
            new CountryModel { Name = "Haiti", ShortName = "HT", Code = "+509", Iso = "HT" },
            new CountryModel { Name = "Holy See (Vatican City State)", ShortName = "VA", Code = "+379", Iso = "VA" },
            new CountryModel { Name = "Honduras", ShortName = "HN", Code = "+504", Iso = "HN" },
            new CountryModel { Name = "Hong Kong", ShortName = "HK", Code = "+852", Iso = "HK" },
            new CountryModel { Name = "Hungary", ShortName = "HU", Code = "+36", Iso = "HU" },
            new CountryModel { Name = "Iceland", ShortName = "IS", Code = "+354", Iso = "IS" },
            new CountryModel { Name = "India", ShortName = "IN", Code = "+91", Iso = "IN" },
            new CountryModel { Name = "Indonesia", ShortName = "ID", Code = "+62", Iso = "ID" },
            new CountryModel
                { Name = "Iran, Islamic Republic of Persian Gulf", ShortName = "IR", Code = "+98", Iso = "IR" },
            new CountryModel { Name = "Iraq", ShortName = "IQ", Code = "+964", Iso = "IQ" },
            new CountryModel { Name = "Ireland", ShortName = "IE", Code = "+353", Iso = "IE" },
            new CountryModel { Name = "Israel", ShortName = "IL", Code = "+972", Iso = "IL" },
            new CountryModel { Name = "Italy", ShortName = "IT", Code = "+39", Iso = "IT" },
            new CountryModel { Name = "Jamaica", ShortName = "JM", Code = "+1876", Iso = "JM" },
            new CountryModel { Name = "Japan", ShortName = "JP", Code = "+81", Iso = "JP" },
            new CountryModel { Name = "Jordan", ShortName = "JO", Code = "+962", Iso = "JO" },
            new CountryModel { Name = "Kazakhstan", ShortName = "KZ", Code = "+77", Iso = "KZ" },
            new CountryModel { Name = "Kenya", ShortName = "KE", Code = "+254", Iso = "KE" },
            new CountryModel { Name = "Kiribati", ShortName = "KI", Code = "+686", Iso = "KI" },
            new CountryModel
                { Name = "Korea, Democratic People's Republic of Korea", ShortName = "KP", Code = "+850", Iso = "KP" },
            new CountryModel { Name = "Korea, Republic of South Korea", ShortName = "KR", Code = "+82", Iso = "KR" },
            new CountryModel { Name = "Kuwait", ShortName = "KW", Code = "+965", Iso = "KW" },
            new CountryModel { Name = "Kyrgyzstan", ShortName = "KG", Code = "+996", Iso = "KG" },
            new CountryModel { Name = "Laos", ShortName = "LA", Code = "+856", Iso = "LA" },
            new CountryModel { Name = "Latvia", ShortName = "LV", Code = "+371", Iso = "LV" },
            new CountryModel { Name = "Lebanon", ShortName = "LB", Code = "+961", Iso = "LB" },
            new CountryModel { Name = "Lesotho", ShortName = "LS", Code = "+266", Iso = "LS" },
            new CountryModel { Name = "Liberia", ShortName = "LR", Code = "+231", Iso = "LR" },
            new CountryModel { Name = "Libyan Arab Jamahiriya", ShortName = "LY", Code = "+218", Iso = "LY" },
            new CountryModel { Name = "Liechtenstein", ShortName = "LI", Code = "+423", Iso = "LI" },
            new CountryModel { Name = "Lithuania", ShortName = "LT", Code = "+370", Iso = "LT" },
            new CountryModel { Name = "Luxembourg", ShortName = "LU", Code = "+352", Iso = "LU" },
            new CountryModel { Name = "Macao", ShortName = "MO", Code = "+853", Iso = "MO" },
            new CountryModel { Name = "Macedonia", ShortName = "MK", Code = "+389", Iso = "MK" },
            new CountryModel { Name = "Madagascar", ShortName = "MG", Code = "+261", Iso = "MG" },
            new CountryModel { Name = "Malawi", ShortName = "MW", Code = "+265", Iso = "MW" },
            new CountryModel { Name = "Malaysia", ShortName = "MY", Code = "+60", Iso = "MY" },
            new CountryModel { Name = "Maldives", ShortName = "MV", Code = "+960", Iso = "MV" },
            new CountryModel { Name = "Mali", ShortName = "ML", Code = "+223", Iso = "ML" },
            new CountryModel { Name = "Malta", ShortName = "MT", Code = "+356", Iso = "MT" },
            new CountryModel { Name = "Marshall Islands", ShortName = "MH", Code = "+692", Iso = "MH" },
            new CountryModel { Name = "Martinique", ShortName = "MQ", Code = "+596", Iso = "MQ" },
            new CountryModel { Name = "Mauritania", ShortName = "MR", Code = "+222", Iso = "MR" },
            new CountryModel { Name = "Mauritius", ShortName = "MU", Code = "+230", Iso = "MU" },
            new CountryModel { Name = "Mayotte", ShortName = "YT", Code = "+262", Iso = "YT" },
            new CountryModel { Name = "Mexico", ShortName = "MX", Code = "+52", Iso = "MX" },
            new CountryModel
                { Name = "Micronesia, Federated States of Micronesia", ShortName = "FM", Code = "+691", Iso = "FM" },
            new CountryModel { Name = "Moldova", ShortName = "MD", Code = "+373", Iso = "MD" },
            new CountryModel { Name = "Monaco", ShortName = "MC", Code = "+377", Iso = "MC" },
            new CountryModel { Name = "Mongolia", ShortName = "MN", Code = "+976", Iso = "MN" },
            new CountryModel { Name = "Montenegro", ShortName = "ME", Code = "+382", Iso = "ME" },
            new CountryModel { Name = "Montserrat", ShortName = "MS", Code = "+1664", Iso = "MS" },
            new CountryModel { Name = "Morocco", ShortName = "MA", Code = "+212", Iso = "MA" },
            new CountryModel { Name = "Mozambique", ShortName = "MZ", Code = "+258", Iso = "MZ" },
            new CountryModel { Name = "Myanmar", ShortName = "MM", Code = "+95", Iso = "MM" },
            new CountryModel { Name = "Namibia", ShortName = "NA", Code = "+264", Iso = "NA" },
            new CountryModel { Name = "Nauru", ShortName = "NR", Code = "+674", Iso = "NR" },
            new CountryModel { Name = "Nepal", ShortName = "NP", Code = "+977", Iso = "NP" },
            new CountryModel { Name = "Netherlands", ShortName = "NL", Code = "+31", Iso = "NL" },
            new CountryModel { Name = "Netherlands Antilles", ShortName = "AN", Code = "+599", Iso = "AN" },
            new CountryModel { Name = "New Caledonia", ShortName = "NC", Code = "+687", Iso = "NC" },
            new CountryModel { Name = "New Zealand", ShortName = "NZ", Code = "+64", Iso = "NZ" },
            new CountryModel { Name = "Nicaragua", ShortName = "NI", Code = "+505", Iso = "NI" },
            new CountryModel { Name = "Niger", ShortName = "NE", Code = "+227", Iso = "NE" },
            new CountryModel { Name = "Nigeria", ShortName = "NG", Code = "+234", Iso = "NG" },
            new CountryModel { Name = "Niue", ShortName = "NU", Code = "+683", Iso = "NU" },
            new CountryModel { Name = "Norfolk Island", ShortName = "NF", Code = "+672", Iso = "NF" },
            new CountryModel { Name = "Northern Mariana Islands", ShortName = "MP", Code = "+1670", Iso = "MP" },
            new CountryModel { Name = "Norway", ShortName = "NO", Code = "+47", Iso = "NO" },
            new CountryModel { Name = "Oman", ShortName = "OM", Code = "+968", Iso = "OM" },
            new CountryModel { Name = "Pakistan", ShortName = "PK", Code = "+92", Iso = "PK" },
            new CountryModel { Name = "Palau", ShortName = "PW", Code = "+680", Iso = "PW" },
            new CountryModel { Name = "Palestinian Territory, Occupied", ShortName = "PS", Code = "+970", Iso = "PS" },
            new CountryModel { Name = "Panama", ShortName = "PA", Code = "+507", Iso = "PA" },
            new CountryModel { Name = "Papua New Guinea", ShortName = "PG", Code = "+675", Iso = "PG" },
            new CountryModel { Name = "Paraguay", ShortName = "PY", Code = "+595", Iso = "PY" },
            new CountryModel { Name = "Peru", ShortName = "PE", Code = "+51", Iso = "PE" },
            new CountryModel { Name = "Philippines", ShortName = "PH", Code = "+63", Iso = "PH" },
            new CountryModel { Name = "Pitcairn", ShortName = "PN", Code = "+872", Iso = "PN" },
            new CountryModel { Name = "Poland", ShortName = "PL", Code = "+48", Iso = "PL" },
            new CountryModel { Name = "Portugal", ShortName = "PT", Code = "+351", Iso = "PT" },
            new CountryModel { Name = "Puerto Rico", ShortName = "PR", Code = "+1939", Iso = "PR" },
            new CountryModel { Name = "Qatar", ShortName = "QA", Code = "+974", Iso = "QA" },
            new CountryModel { Name = "Reunion", ShortName = "RE", Code = "+262", Iso = "RE" },
            new CountryModel { Name = "Romania", ShortName = "RO", Code = "+40", Iso = "RO" },
            new CountryModel { Name = "Russia", ShortName = "RU", Code = "+7", Iso = "RU" },
            new CountryModel { Name = "Rwanda", ShortName = "RW", Code = "+250", Iso = "RW" },
            new CountryModel { Name = "Saint Barthelemy", ShortName = "BL", Code = "+590", Iso = "BL" },
            new CountryModel
                { Name = "Saint Helena, Ascension and Tristan Da Cunha", ShortName = "SH", Code = "+290", Iso = "SH" },
            new CountryModel { Name = "Saint Kitts and Nevis", ShortName = "KN", Code = "+1869", Iso = "KN" },
            new CountryModel { Name = "Saint Lucia", ShortName = "LC", Code = "+1758", Iso = "LC" },
            new CountryModel { Name = "Saint Martin", ShortName = "MF", Code = "+590", Iso = "MF" },
            new CountryModel { Name = "Saint Pierre and Miquelon", ShortName = "PM", Code = "+508", Iso = "PM" },
            new CountryModel
                { Name = "Saint Vincent and the Grenadines", ShortName = "VC", Code = "+1784", Iso = "VC" },
            new CountryModel { Name = "Samoa", ShortName = "WS", Code = "+685", Iso = "WS" },
            new CountryModel { Name = "San Marino", ShortName = "SM", Code = "+378", Iso = "SM" },
            new CountryModel { Name = "Sao Tome and Principe", ShortName = "ST", Code = "+239", Iso = "ST" },
            new CountryModel { Name = "Saudi Arabia", ShortName = "SA", Code = "+966", Iso = "SA" },
            new CountryModel { Name = "Senegal", ShortName = "SN", Code = "+221", Iso = "SN" },
            new CountryModel { Name = "Serbia", ShortName = "RS", Code = "+381", Iso = "RS" },
            new CountryModel { Name = "Seychelles", ShortName = "SC", Code = "+248", Iso = "SC" },
            new CountryModel { Name = "Sierra Leone", ShortName = "SL", Code = "+232", Iso = "SL" },
            new CountryModel { Name = "Singapore", ShortName = "SG", Code = "+65", Iso = "SG" },
            new CountryModel { Name = "Slovakia", ShortName = "SK", Code = "+421", Iso = "SK" },
            new CountryModel { Name = "Slovenia", ShortName = "SI", Code = "+386", Iso = "SI" },
            new CountryModel { Name = "Solomon Islands", ShortName = "SB", Code = "+677", Iso = "SB" },
            new CountryModel { Name = "Somalia", ShortName = "SO", Code = "+252", Iso = "SO" },
            new CountryModel { Name = "South Africa", ShortName = "ZA", Code = "+27", Iso = "ZA" },
            new CountryModel
                { Name = "South Georgia and the South Sandwich Islands", ShortName = "GS", Code = "+500", Iso = "GS" },
            new CountryModel { Name = "South Sudan", ShortName = "SS", Code = "+211", Iso = "SS" },
            new CountryModel { Name = "Spain", ShortName = "ES", Code = "+34", Iso = "ES" },
            new CountryModel { Name = "Sri Lanka", ShortName = "LK", Code = "+94", Iso = "LK" },
            new CountryModel { Name = "Sudan", ShortName = "SD", Code = "+249", Iso = "SD" },
            new CountryModel { Name = "Suriname", ShortName = "SR", Code = "+597", Iso = "SR" },
            new CountryModel { Name = "Svalbard and Jan Mayen", ShortName = "SJ", Code = "+47", Iso = "SJ" },
            new CountryModel { Name = "Swaziland", ShortName = "SZ", Code = "+268", Iso = "SZ" },
            new CountryModel { Name = "Sweden", ShortName = "SE", Code = "+46", Iso = "SE" },
            new CountryModel { Name = "Switzerland", ShortName = "CH", Code = "+41", Iso = "CH" },
            new CountryModel { Name = "Syrian Arab Republic", ShortName = "SY", Code = "+963", Iso = "SY" },
            new CountryModel { Name = "Taiwan", ShortName = "TW", Code = "+886", Iso = "TW" },
            new CountryModel { Name = "Tajikistan", ShortName = "TJ", Code = "+992", Iso = "TJ" },
            new CountryModel
                { Name = "Tanzania, United Republic of Tanzania", ShortName = "TZ", Code = "+255", Iso = "TZ" },
            new CountryModel { Name = "Thailand", ShortName = "TH", Code = "+66", Iso = "TH" },
            new CountryModel { Name = "Timor-Leste", ShortName = "TL", Code = "+670", Iso = "TL" },
            new CountryModel { Name = "Togo", ShortName = "TG", Code = "+228", Iso = "TG" },
            new CountryModel { Name = "Tokelau", ShortName = "TK", Code = "+690", Iso = "TK" },
            new CountryModel { Name = "Tonga", ShortName = "TO", Code = "+676", Iso = "TO" },
            new CountryModel { Name = "Trinidad and Tobago", ShortName = "TT", Code = "+1868", Iso = "TT" },
            new CountryModel { Name = "Tunisia", ShortName = "TN", Code = "+216", Iso = "TN" },
            new CountryModel { Name = "Turkey", ShortName = "TR", Code = "+90", Iso = "TR" },
            new CountryModel { Name = "Turkmenistan", ShortName = "TM", Code = "+993", Iso = "TM" },
            new CountryModel { Name = "Turks and Caicos Islands", ShortName = "TC", Code = "+1649", Iso = "TC" },
            new CountryModel { Name = "Tuvalu", ShortName = "TV", Code = "+688", Iso = "TV" },
            new CountryModel { Name = "Uganda", ShortName = "UG", Code = "+256", Iso = "UG" },
            new CountryModel { Name = "Ukraine", ShortName = "UA", Code = "+380", Iso = "UA" },
            new CountryModel { Name = "United Arab Emirates", ShortName = "AE", Code = "+971", Iso = "AE" },
            new CountryModel { Name = "United Kingdom", ShortName = "UK", Code = "+44", Iso = "GB" },
            new CountryModel { Name = "United States", ShortName = "US", Code = "+1", Iso = "US" },
            new CountryModel { Name = "Uruguay", ShortName = "UY", Code = "+598", Iso = "UY" },
            new CountryModel { Name = "Uzbekistan", ShortName = "UZ", Code = "+998", Iso = "UZ" },
            new CountryModel { Name = "Vanuatu", ShortName = "VU", Code = "+678", Iso = "VU" },
            new CountryModel
                { Name = "Venezuela, Bolivarian Republic of Venezuela", ShortName = "VE", Code = "+58", Iso = "VE" },
            new CountryModel { Name = "Vietnam", ShortName = "VN", Code = "+84", Iso = "VN" },
            new CountryModel { Name = "Virgin Islands, British", ShortName = "VG", Code = "+1284", Iso = "VG" },
            new CountryModel { Name = "Virgin Islands, U.S.", ShortName = "VI", Code = "+1340", Iso = "VI" },
            new CountryModel { Name = "Wallis and Futuna", ShortName = "WF", Code = "+681", Iso = "WF" },
            new CountryModel { Name = "Yemen", ShortName = "YE", Code = "+967", Iso = "YE" },
            new CountryModel { Name = "Zambia", ShortName = "ZM", Code = "+260", Iso = "ZM" },
            new CountryModel { Name = "Zimbabwe", ShortName = "ZW", Code = "+263", Iso = "ZW" },
        };
    }
}